# Generated by Django 3.2.3 on 2021-07-02 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='Rut')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='core\\static\\img\x0coto')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre_completo')),
                ('telefono', models.IntegerField(verbose_name='telefono')),
                ('direccion', models.CharField(max_length=70, verbose_name='direccion')),
                ('email', models.CharField(max_length=70, verbose_name='email')),
                ('pais', models.CharField(max_length=50, verbose_name='pais')),
                ('contraseña', models.CharField(max_length=70, verbose_name='contraseña')),
            ],
        ),
    ]
