# Generated by Django 3.2.3 on 2021-07-05 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_colaborador_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idPais', models.IntegerField(primary_key=True, serialize=False, verbose_name='id pais')),
                ('namePais', models.CharField(max_length=50, verbose_name='Nombre pais')),
            ],
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pais'),
        ),
    ]
